/* =========================================================
   Om Properties — Modular single-file JavaScript
   Features: nav, menu, hero, search, counters, sliders,
   modals, splash, page transitions, theme, scroll top,
   loading, toasts, validation and animations.
========================================================= */

const $ = (selector, scope = document) => scope.querySelector(selector);
const $$ = (selector, scope = document) => [...scope.querySelectorAll(selector)];

const images = {
  home: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=82',
  villa: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=82',
  office: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82',
  farm: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=82',
  interiors: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=82',
  plot: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=82',
  land: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1400&q=82',
  shop: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82'
};

const properties = [
  { id:'OP-101', title:'Premium Residential Plot in Sector 20', location:'Sector 20, Kaithal', price:'₹42 Lac', amount:4200000, type:'Plot', status:'For Sale', area:'180 sq yd', image:images.home, gallery:[images.home, images.villa, images.interiors], summary:'Registry-ready plot in a developed sector with wide road access and family-friendly surroundings.' },
  { id:'OP-102', title:'Main Road Commercial SCO', location:'Ambala Road, Kaithal', price:'₹1.35 Cr', amount:13500000, type:'Commercial', status:'Investment', area:'92 sq yd', image:images.office, gallery:[images.office, images.shop, images.interiors], summary:'High-visibility commercial SCO suitable for retail, clinic, showroom or office use.' },
  { id:'OP-103', title:'Fertile Agricultural Land on Highway Belt', location:'Kaithal-Jind Highway', price:'₹98 Lac', amount:9800000, type:'Agricultural', status:'For Sale', area:'6 acres', image:images.farm, gallery:[images.farm, images.land, images.plot], summary:'Contiguous agricultural holding with dependable approach and productive soil profile.' },
  { id:'OP-104', title:'Investment Farmhouse Land', location:'Near Jind Bypass', price:'₹78 Lac', amount:7800000, type:'Farmhouse', status:'Investment', area:'2.5 acres', image:images.land, gallery:[images.land, images.villa, images.farm], summary:'Lifestyle and investment parcel close to Jind Bypass with peaceful surroundings.' },
  { id:'OP-105', title:'Modern Family Home near Pehowa Chowk', location:'Pehowa Chowk, Kaithal', price:'₹86 Lac', amount:8600000, type:'Residential', status:'For Sale', area:'220 sq yd', image:images.villa, gallery:[images.villa, images.interiors, images.home], summary:'Move-in-ready residential home with premium interiors near Kaithal city conveniences.' },
  { id:'OP-106', title:'Leased Office Space in Civil Lines', location:'Civil Lines, Jind', price:'₹55,000 / month', amount:55000, type:'Commercial', status:'For Rent', area:'1,450 sq ft', image:images.shop, gallery:[images.shop, images.office, images.interiors], summary:'Professionally maintained office floor available for lease in a central Jind location.' }
];

const services = [['🏡','Buy / Sell Homes','Verified residential deals with family-first shortlisting.'],['🏢','Commercial Growth','Retail, SCO, office and rental-income opportunities.'],['🌿','Land Banking','Agricultural and highway-belt land with document guidance.'],['📜','Plots & Registry','Clear-title plots, negotiation and registry coordination.'],['📈','Investment Desk','ROI-led advisory for appreciation and rentals.'],['✅','Legal Docs','Paperwork readiness, checklists and closing support.'],['🛡️','NRI Support','Remote shortlists, video walkthroughs and visit planning.'],['🤝','Rental Services','Tenant-ready commercial and residential matching.']];
const tools = [['🤖','AI property assistant'],['💬','Live chat / WhatsApp'],['🧮','EMI & ROI calculators'],['🎥','360° tour ready'],['🔔','Saved searches'],['🧭','Smart dashboard']];
const testimonials = [{name:'Rajesh Malik',role:'Plot Buyer',text:'Om Properties handled our plot purchase with transparent pricing, clear papers and quick registry support.'},{name:'Neha Sharma',role:'Home Buyer',text:'Professional guidance and genuine options in Kaithal. Their team understood our family requirements perfectly.'},{name:'Vikram Hooda',role:'Land Investor',text:'Excellent investment advice for agricultural land near Jind. Documentation support was smooth and reliable.'}];
const locations = ['Kaithal','Jind','Ambala Road','Sector 20','Pehowa Chowk','Jind Bypass','Civil Lines','Highway Belt'];
let heroIndex = 0, sliderPage = 0, carouselIndex = 0, filtered = [...properties];

function toast(message){ const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2800); }
function initSplash(){ window.addEventListener('load',()=>setTimeout(()=>$('#splash').classList.add('hide'),650)); }
function initNavigation(){ $('#menuBtn').addEventListener('click',()=>$('#nav').classList.toggle('open')); $$('#nav a').forEach(a=>a.addEventListener('click',()=>$('#nav').classList.remove('open'))); window.addEventListener('scroll',()=>{ $('#header').classList.toggle('scrolled',scrollY>20); $('#progress').style.width = `${(scrollY/(document.body.scrollHeight-innerHeight))*100}%`; $('#scrollTop').classList.toggle('show',scrollY>650); }); $('#scrollTop').addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'})); }
function initTheme(){ const saved = localStorage.getItem('theme'); if(saved) document.body.dataset.theme=saved; $('#themeToggle').addEventListener('click',()=>{ const light = document.body.dataset.theme !== 'light'; document.body.dataset.theme = light ? 'light' : 'dark'; localStorage.setItem('theme', document.body.dataset.theme); $('#themeToggle').textContent = light ? '☀' : '☾'; toast(`${light ? 'Light' : 'Dark'} theme enabled`); }); }
function renderHero(){ const p = properties[heroIndex % 3]; $('#heroBg').style.backgroundImage = `url(${p.image})`; $('#heroCardImage').src = p.gallery[1]; $('#heroCardImage').alt = p.title; $('#heroMeta').textContent = `${p.status} • ${p.type} • ${p.location}`; $('#heroTitle').textContent = p.title; $('#heroPrice').textContent = p.price; $('#heroTabs').innerHTML = properties.slice(0,3).map((item,i)=>`<button class="${i===heroIndex?'active':''}" data-hero="${i}"><small>${item.id}</small><br><b>${item.location}</b></button>`).join(''); $$('[data-hero]').forEach(btn=>btn.addEventListener('click',()=>{heroIndex=+btn.dataset.hero;renderHero();})); }
function initHero(){ renderHero(); setInterval(()=>{heroIndex=(heroIndex+1)%3;renderHero();},6000); }
function renderCards(){ $('#propertyTrack').innerHTML = filtered.slice(sliderPage, sliderPage + 3).map(p=>`<article class="property-card"><img src="${p.image}" alt="${p.title}"><div class="property-body"><p class="eyebrow">${p.status} · ${p.type}</p><h3>${p.title}</h3><div class="property-meta"><span>${p.location}</span><span>${p.area}</span></div><p>${p.summary}</p><div class="property-meta"><strong class="price">${p.price}</strong><button class="btn glass" data-modal="visitModal">Enquire</button></div></div></article>`).join(''); $('#emptyState').style.display = filtered.length ? 'none' : 'block'; $$('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal))); }
function renderStatic(){ $('#serviceGrid').innerHTML = services.map(s=>`<article class="service-card reveal"><i>${s[0]}</i><h3>${s[1]}</h3><p>${s[2]}</p></article>`).join(''); $('#toolGrid').innerHTML = tools.map(t=>`<article class="tool-card reveal"><i>${t[0]}</i><h3>${t[1]}</h3><p>Interactive luxury UI pattern ready for future backend wiring.</p></article>`).join(''); $('#testimonialGrid').innerHTML = testimonials.map(t=>`<article class="testimonial reveal"><p>★★★★★</p><blockquote>“${t.text}”</blockquote><strong>${t.name}</strong><small>${t.role}</small></article>`).join(''); $('#locationChips').innerHTML = locations.map(l=>`<button type="button" data-chip="${l}">#${l.replaceAll(' ','')}</button>`).join(''); $$('[data-chip]').forEach(c=>c.addEventListener('click',()=>{$('#searchInput').value=c.dataset.chip; filterProperties();})); renderCards(); }
function filterProperties(){ const q = $('#searchInput').value.toLowerCase().trim(); const type = $('#typeFilter').value; const budget = $('#budgetFilter').value; filtered = properties.filter(p => (!q || `${p.title} ${p.location} ${p.type} ${p.summary}`.toLowerCase().includes(q)) && (type === 'All' || p.type === type) && (budget === 'all' || p.amount <= +budget)); sliderPage = 0; renderCards(); toast(`${filtered.length} curated listing${filtered.length === 1 ? '' : 's'} found`); }
function initSearchAndSlider(){ $('#searchForm').addEventListener('submit',e=>{e.preventDefault();filterProperties();}); $('#prevProperty').addEventListener('click',()=>{sliderPage=Math.max(0,sliderPage-1);renderCards();}); $('#nextProperty').addEventListener('click',()=>{sliderPage=(sliderPage+3>=filtered.length)?0:sliderPage+1;renderCards();}); }
function initCarousel(){ const gallery = properties.flatMap(p=>p.gallery); const show=()=>{$('#carouselImage').src=gallery[carouselIndex];}; $('#carouselPrev').addEventListener('click',()=>{carouselIndex=(carouselIndex-1+gallery.length)%gallery.length;show();}); $('#carouselNext').addEventListener('click',()=>{carouselIndex=(carouselIndex+1)%gallery.length;show();}); setInterval(()=>{$('#carouselNext').click();},4500); show(); }
function initAnimations(){ const observer = new IntersectionObserver(entries=>entries.forEach(entry=>{ if(entry.isIntersecting){ entry.target.classList.add('visible'); const counters = $$('[data-counter]', entry.target); counters.forEach(animateCounter); observer.unobserve(entry.target); }}),{threshold:.18}); $$('.reveal,.stats,.trust-grid').forEach(el=>observer.observe(el)); }
function animateCounter(el){ const target = parseFloat(el.dataset.counter); const decimals = String(target).includes('.') ? 1 : 0; let current = 0; const step = target / 48; const timer = setInterval(()=>{ current += step; if(current >= target){ current = target; clearInterval(timer); } el.textContent = current.toFixed(decimals) + (target===100?'%':''); },24); }
function openModal(id){ const modal = document.getElementById(id); if(modal?.showModal) modal.showModal(); else toast('Viewing request noted.'); }
function initModals(){ $$('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal))); $$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close())); }
function initForms(){ $('#contactForm').addEventListener('submit',e=>{ e.preventDefault(); if(!e.currentTarget.checkValidity()){ e.currentTarget.reportValidity(); toast('Please complete all required fields.'); return; } e.currentTarget.reset(); toast('Thank you. Your private request has been received.'); }); }
function initPageTransitions(){ $$('a[href^="#"]').forEach(link=>link.addEventListener('click',()=>document.body.animate([{opacity:.82},{opacity:1}],{duration:260}))); }

initSplash(); initNavigation(); initTheme(); initHero(); renderStatic(); initSearchAndSlider(); initCarousel(); initAnimations(); initModals(); initForms(); initPageTransitions();
