const $ = (selector, scope = document) => scope.querySelector(selector);
const $$ = (selector, scope = document) => [...scope.querySelectorAll(selector)];
const rupee = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);

const images = {
  residence: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=82',
  interiors: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=82',
  villa: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=82',
  office: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82',
  shop: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82',
  farm: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=82',
  land: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1400&q=82',
  plot: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=82'
};

const properties = [
  { id:'OP-101', title:'Registry-Ready Plot in Sector 20', location:'Sector 20, Kaithal', price:'₹42 Lac', amount:4200000, type:'Plot', status:'For Sale', area:'180 sq yd', beds:'—', image:images.plot, gallery:[images.plot, images.villa, images.interiors], summary:'A clean-title residential plot in a developed pocket with wide approach roads, family housing nearby and quick registry coordination.' },
  { id:'OP-102', title:'Main Road Commercial SCO', location:'Ambala Road, Kaithal', price:'₹1.35 Cr', amount:13500000, type:'Commercial', status:'Investment', area:'92 sq yd', beds:'Retail', image:images.office, gallery:[images.office, images.shop, images.interiors], summary:'High-visibility SCO for clinic, showroom, boutique office or rental-income strategy on an active commercial stretch.' },
  { id:'OP-103', title:'Highway Belt Agricultural Holding', location:'Kaithal-Jind Highway', price:'₹98 Lac', amount:9800000, type:'Agricultural', status:'For Sale', area:'6 acres', beds:'Land', image:images.farm, gallery:[images.farm, images.land, images.plot], summary:'Contiguous fertile land with dependable access, suitable for cultivation, long-term holding and corridor-led appreciation.' },
  { id:'OP-104', title:'Farmhouse Parcel near Jind Bypass', location:'Jind Bypass', price:'₹78 Lac', amount:7800000, type:'Farmhouse', status:'Lifestyle', area:'2.5 acres', beds:'Land', image:images.land, gallery:[images.land, images.villa, images.farm], summary:'A peaceful parcel for weekend living or future farmhouse development close to Jind connectivity nodes.' },
  { id:'OP-105', title:'Modern Family Home near Pehowa Chowk', location:'Pehowa Chowk, Kaithal', price:'₹86 Lac', amount:8600000, type:'Residential', status:'For Sale', area:'220 sq yd', beds:'4 beds', image:images.residence, gallery:[images.residence, images.interiors, images.villa], summary:'Move-in-ready residence with refined interiors, parking, daily conveniences nearby and a practical family layout.' },
  { id:'OP-106', title:'Managed Office Floor in Civil Lines', location:'Civil Lines, Jind', price:'₹55,000 / month', amount:55000, type:'Commercial', status:'For Rent', area:'1,450 sq ft', beds:'Office', image:images.shop, gallery:[images.shop, images.office, images.interiors], summary:'Professionally maintained office floor with central access for finance, consulting, healthcare or education businesses.' }
];
const services = [['🏡','Home buying & selling','Private shortlists, price negotiation and family-focused location guidance for Kaithal and Jind homes.'],['🏢','Commercial leasing & sales','SCOs, showrooms, offices and rental assets assessed for visibility, frontage and tenant fit.'],['🌿','Agricultural land advisory','Field visits, access checks and documentation guidance for productive and investment land.'],['📜','Plot registry support','Title-readiness checklists, seller coordination, token planning and registry-day assistance.'],['📈','Investor desk','Rental yield, appreciation corridor and exit-planning conversations for disciplined investors.'],['🧾','Valuation requests','Local comparable analysis and practical pricing guidance before you sell or buy.'],['🎥','Remote buyer support','Video walkthroughs, WhatsApp updates and document scans for outstation and NRI clients.'],['🤝','Visit concierge','Route planning, appointment scheduling and post-visit decision notes for serious buyers.']];
const tools = [['♡','Favorites saved locally','Shortlist properties in this browser and return without losing your context.'],['⇄','Side-by-side comparison','Compare price, location, area and use case before booking visits.'],['🧮','EMI planning','Estimate affordability instantly using practical loan assumptions.'],['🗺','Google Maps embedded','Orient yourself around Kaithal, Jind and highway corridors.'],['💬','WhatsApp + click-to-call','Reach the advisory desk from any screen on mobile or desktop.'],['🔔','Toast notifications','Clear feedback for saved listings, forms, empty states and interactions.']];
const testimonials = [{name:'Rajesh Malik',role:'Plot Buyer, Sector 20',text:'The team showed only relevant plots, explained the papers clearly and stayed with us through registry day.'},{name:'Neha Sharma',role:'Home Buyer, Kaithal',text:'We wanted a practical family home near schools. Om Properties filtered the noise and negotiated with patience.'},{name:'Vikram Hooda',role:'Land Investor, Jind Road',text:'Their local understanding of approach roads and future corridor value helped us buy with confidence.'}];
const insights = ['Why Sector 20 remains a preferred family housing pocket in Kaithal','Commercial frontage checklist before leasing on Ambala Road','Agricultural land documents buyers should review before token payment'];
const faqs = [['Do you verify every listing?','Listings are prepared as verified mock data for this front-end build and structured so real ownership, title and availability checks can be connected to a backend.'],['Can I schedule visits on WhatsApp?','Yes. Use the floating WhatsApp button or the visit form. The UI is ready for calendar and CRM integration.'],['Do you help with valuation?','Yes. The contact form includes valuation requests, and the advisory flow supports comparable pricing conversations for Kaithal and Jind.']];
const locations = ['Kaithal','Jind','Ambala Road','Sector 20','Pehowa Chowk','Jind Bypass','Civil Lines','Highway Belt'];
let heroIndex = 0, carouselIndex = 0, filtered = [...properties];
let saved = JSON.parse(localStorage.getItem('savedProperties') || '[]');
let recent = JSON.parse(localStorage.getItem('recentProperties') || '[]');
let compared = [];

function toast(message){ const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(()=>el.classList.remove('show'),3000); }
function initSplash(){ window.addEventListener('load',()=>setTimeout(()=>$('#splash').classList.add('hide'),720)); }
function initNavigation(){ $('#menuBtn').addEventListener('click',e=>{ const open = $('#nav').classList.toggle('open'); e.currentTarget.setAttribute('aria-expanded', open); e.currentTarget.setAttribute('aria-label', open ? 'Close menu' : 'Open menu'); }); $$('#nav a').forEach(a=>a.addEventListener('click',()=>{ $('#nav').classList.remove('open'); $('#menuBtn').setAttribute('aria-expanded','false'); })); const onScroll=()=>{ const max = Math.max(1, document.body.scrollHeight - innerHeight); $('#header').classList.toggle('scrolled',scrollY>24); $('#progress').style.width = `${Math.min(100,(scrollY/max)*100)}%`; $('#scrollTop').classList.toggle('show',scrollY>650); const current = [...$$('#nav a')].reverse().find(a=>{ const section = document.querySelector(a.getAttribute('href')); return section && section.offsetTop <= scrollY + 160; }); $$('#nav a').forEach(a=>a.classList.toggle('active', a===current)); }; window.addEventListener('scroll',onScroll,{passive:true}); onScroll(); $('#scrollTop').addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'})); }
function initTheme(){ const savedTheme = localStorage.getItem('theme') || 'dark'; document.body.dataset.theme=savedTheme; $('#themeToggle').textContent = savedTheme === 'light' ? '☀' : '☾'; $('#themeToggle').addEventListener('click',()=>{ const light = document.body.dataset.theme !== 'light'; document.body.dataset.theme = light ? 'light' : 'dark'; localStorage.setItem('theme', document.body.dataset.theme); $('#themeToggle').textContent = light ? '☀' : '☾'; toast(`${light ? 'Light' : 'Dark'} theme enabled`); }); }
function renderHero(){ const p = properties[heroIndex % 3]; $('#heroBg').style.backgroundImage = `url(${p.image})`; $('#heroCardImage').src = p.gallery[1]; $('#heroMeta').textContent = `${p.status} • ${p.type} • ${p.location}`; $('#heroTitle').textContent = p.title; $('#heroPrice').textContent = p.price; $('#heroTabs').innerHTML = properties.slice(0,3).map((item,i)=>`<button class="${i===heroIndex?'active':''}" data-hero="${i}"><small>${item.id}</small><br><b>${item.location}</b></button>`).join(''); $$('[data-hero]').forEach(btn=>btn.addEventListener('click',()=>{heroIndex=+btn.dataset.hero;renderHero();})); }
function propertyCard(p){ const isSaved = saved.includes(p.id); const isCompared = compared.includes(p.id); return `<article class="property-card reveal"><button class="save-btn ${isSaved?'active':''}" data-save="${p.id}" aria-label="Save ${p.title}">${isSaved?'♥':'♡'}</button><span class="property-ribbon">${p.status}</span><img src="${p.image}" alt="${p.title}" loading="lazy"><div class="property-body"><p class="eyebrow">${p.status} · ${p.type}</p><h3>${p.title}</h3><div class="property-meta"><span>${p.location}</span><span>${p.area}</span></div><p>${p.summary}</p><div class="property-actions"><strong class="price">${p.price}</strong><button class="mini-btn ${isCompared?'active':''}" data-compare="${p.id}" aria-pressed="${isCompared}">${isCompared?'Selected':'Compare'}</button><button class="share-btn" data-share="${p.id}">Share</button><button class="btn glass" data-visit="${p.id}" data-modal="visitModal">Visit</button></div></div></article>`; }
function renderCards(){ $('#propertyTrack').innerHTML = filtered.map(propertyCard).join(''); $('#emptyState').style.display = filtered.length ? 'none' : 'block'; $('#resultCount').textContent = `${filtered.length} listing${filtered.length===1?'':'s'}`; renderRecent(); bindDynamicButtons(); initAnimations(); }
function bindDynamicButtons(){ $$('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal))); $$('[data-save]').forEach(btn=>btn.addEventListener('click',()=>{ const id = btn.dataset.save; saved = saved.includes(id) ? saved.filter(x=>x!==id) : [...saved,id]; localStorage.setItem('savedProperties', JSON.stringify(saved)); toast(saved.includes(id) ? 'Property added to favorites' : 'Property removed from favorites'); renderCards(); })); $$('[data-compare]').forEach(btn=>btn.addEventListener('click',()=>{ const id = btn.dataset.compare; compared = compared.includes(id) ? compared.filter(x=>x!==id) : [...compared,id].slice(-3); toast(`${compared.length} selected for comparison`); renderCards(); })); $$('[data-share]').forEach(btn=>btn.addEventListener('click',()=>shareProperty(btn.dataset.share))); $$('[data-visit]').forEach(btn=>btn.addEventListener('click',()=>markRecent(btn.dataset.visit))); }
function renderRecent(){ const wrap = $('#recentlyViewed'); if(!wrap) return; const rows = recent.map(id=>properties.find(p=>p.id===id)).filter(Boolean); wrap.classList.toggle('show', rows.length>0); wrap.innerHTML = rows.length ? `<h3>Recently viewed</h3><div class="recent-list">${rows.map(p=>`<article><img src="${p.image}" alt="${p.title}" loading="lazy"><div><strong>${p.title}</strong><br><small>${p.location} · ${p.price}</small></div></article>`).join('')}</div>` : ''; }
function markRecent(id){ recent = [id, ...recent.filter(x=>x!==id)].slice(0,4); localStorage.setItem('recentProperties', JSON.stringify(recent)); renderRecent(); }
async function shareProperty(id){ const p = properties.find(item=>item.id===id); if(!p) return; markRecent(id); const text = `${p.title} in ${p.location} — ${p.price}`; const url = `${location.origin}${location.pathname}#properties`; if(navigator.share){ await navigator.share({title:p.title,text,url}).catch(()=>{}); } else { await navigator.clipboard?.writeText(`${text} ${url}`); toast('Property link copied to clipboard'); } }
function renderStatic(){ $('#serviceGrid').innerHTML = services.map(s=>`<article class="service-card reveal"><i>${s[0]}</i><h3>${s[1]}</h3><p>${s[2]}</p></article>`).join(''); $('#toolGrid').innerHTML = tools.map(t=>`<article class="tool-card reveal"><i>${t[0]}</i><h3>${t[1]}</h3><p>${t[2]}</p></article>`).join(''); $('#testimonialGrid').innerHTML = testimonials.map(t=>`<article class="testimonial reveal"><p>★★★★★</p><blockquote>“${t.text}”</blockquote><strong>${t.name}</strong><small>${t.role}</small></article>`).join(''); $('#insightGrid').innerHTML = insights.map((t,i)=>`<article class="insight-card reveal"><span>0${i+1}</span><h3>${t}</h3><p>Market notes prepared for practical buyers who want grounded local context before making site visits.</p></article>`).join(''); $('#faqList').innerHTML = faqs.map(f=>`<details class="reveal"><summary>${f[0]}</summary><p>${f[1]}</p></details>`).join(''); $('#locationChips').innerHTML = locations.map(l=>`<button type="button" data-chip="${l}">#${l.replaceAll(' ','')}</button>`).join(''); $$('[data-chip]').forEach(c=>c.addEventListener('click',()=>{$('#searchInput').value=c.dataset.chip; filterProperties();})); renderCards(); }
function updateSuggestions(){ const q = $('#searchInput').value.toLowerCase().trim(); const matches = [...new Set(properties.flatMap(p=>[p.location,p.type,p.title]).filter(v=>v.toLowerCase().includes(q)))].slice(0,5); $('#searchSuggestions').innerHTML = q && matches.length ? matches.map(m=>`<button type="button" role="option" data-suggest="${m}">${m}</button>`).join('') : ''; $('#searchSuggestions').classList.toggle('show', q && matches.length); $$('[data-suggest]').forEach(b=>b.addEventListener('mousedown',()=>{ $('#searchInput').value=b.dataset.suggest; filterProperties(); hideSuggestions(); })); }
function hideSuggestions(){ $('#searchSuggestions')?.classList.remove('show'); }
function filterProperties(){ const q = $('#searchInput').value.toLowerCase().trim(); const type = $('#typeFilter').value; const budget = $('#budgetFilter').value; filtered = properties.filter(p => (!q || `${p.title} ${p.location} ${p.type} ${p.summary}`.toLowerCase().includes(q)) && (type === 'All' || p.type === type) && (budget === 'all' || p.amount <= +budget)); const sort = $('#sortFilter').value; if(sort === 'low') filtered.sort((a,b)=>a.amount-b.amount); if(sort === 'high') filtered.sort((a,b)=>b.amount-a.amount); renderCards(); toast(filtered.length ? `${filtered.length} curated listing${filtered.length === 1 ? '' : 's'} found` : 'No listings matched this search'); }
function initSearch(){ $('#searchForm').addEventListener('submit',e=>{e.preventDefault();filterProperties(); hideSuggestions();}); ['searchInput','typeFilter','budgetFilter','sortFilter'].forEach(id=>$('#'+id).addEventListener('input',filterProperties)); $('#searchInput').addEventListener('input',updateSuggestions); $('#searchInput').addEventListener('blur',()=>setTimeout(hideSuggestions,150)); $('#clearSavedBtn').addEventListener('click',()=>{saved=[]; localStorage.removeItem('savedProperties'); toast('Favorites cleared'); renderCards();}); $('#compareBtn').addEventListener('click',showCompare); }
function showCompare(){ if(!compared.length){ toast('Select up to three properties to compare'); return; } const rows = compared.map(id=>properties.find(p=>p.id===id)).filter(Boolean); $('#compareContent').innerHTML = `<div class="compare-grid">${rows.map(p=>`<article><img src="${p.image}" alt="${p.title}"><h3>${p.title}</h3><p>${p.location}</p><strong>${p.price}</strong><small>${p.type} • ${p.area}</small></article>`).join('')}</div>`; openModal('compareModal'); }
function initCarousel(){ const gallery = properties.flatMap(p=>p.gallery); const show=()=>{$('#carouselImage').src=gallery[carouselIndex];}; $('#carouselPrev').addEventListener('click',()=>{carouselIndex=(carouselIndex-1+gallery.length)%gallery.length;show();}); $('#carouselNext').addEventListener('click',()=>{carouselIndex=(carouselIndex+1)%gallery.length;show();}); setInterval(()=>{$('#carouselNext').click();},5000); show(); }
function initCalculator(){ const calc=()=>{ const principal=+$('#loanAmount').value, rate=+$('#loanRate').value/12/100, months=+$('#loanYears').value*12; const emi = principal*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1); $('#emiOutput').textContent = `${rupee(Number.isFinite(emi)?emi:0)} / month`; }; $$('#emiForm input').forEach(input=>input.addEventListener('input',calc)); calc(); }
function initAnimations(){ if(window.omObserver) window.omObserver.disconnect(); window.omObserver = new IntersectionObserver(entries=>entries.forEach(entry=>{ if(entry.isIntersecting){ entry.target.classList.add('visible'); $$('[data-counter]', entry.target).forEach(animateCounter); window.omObserver.unobserve(entry.target); }}),{threshold:.16}); $$('.reveal,.stats,.trust-grid').forEach(el=>window.omObserver.observe(el)); }
function animateCounter(el){ if(el.dataset.done) return; el.dataset.done = 'true'; const target = parseFloat(el.dataset.counter); const decimals = String(target).includes('.') ? 1 : 0; let current = 0; const timer = setInterval(()=>{ current += target / 48; if(current >= target){ current = target; clearInterval(timer); } el.textContent = current.toFixed(decimals) + (target===98 || target===100?'%':''); },22); }
function openModal(id){ const modal = document.getElementById(id); modal?.showModal ? modal.showModal() : toast('Request captured.'); }
function initModalsAndForms(){ const visitDate = $('#visitForm input[type="date"]'); if(visitDate) visitDate.min = new Date().toISOString().split('T')[0]; $$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close())); ['contactForm','visitForm','newsletterForm'].forEach(id=>$('#'+id)?.addEventListener('submit',e=>{ e.preventDefault(); $$('input,select,textarea', e.currentTarget).forEach(field=>field.classList.toggle('field-error', !field.checkValidity())); if(!e.currentTarget.checkValidity()){ e.currentTarget.reportValidity(); toast('Please complete the highlighted fields.'); return; } e.currentTarget.reset(); toast(id==='visitForm'?'Visit request received. We will confirm shortly.':id==='newsletterForm'?'You are subscribed to the market brief.':'Thank you. Your advisory request has been received.'); e.currentTarget.closest('dialog')?.close(); })); }
function initPageTransitions(){ $$('a[href^="#"]').forEach(link=>link.addEventListener('click',()=>document.body.animate([{opacity:.84},{opacity:1}],{duration:260}))); }

initSplash(); initNavigation(); initTheme(); renderHero(); setInterval(()=>{heroIndex=(heroIndex+1)%3;renderHero();},6500); renderStatic(); initSearch(); initCarousel(); initCalculator(); initAnimations(); initModalsAndForms(); initPageTransitions();
