'use client';

import Image from 'next/image';
import { motion, useScroll, useSpring } from 'framer-motion';
import { Building2, ChevronUp, FileCheck2, Home, Landmark, Leaf, Mail, MapPin, Menu, Moon, Phone, Search, ShieldCheck, Sparkles, Star, Sun, TrendingUp, Users, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { properties, testimonials } from '@/data/site';

const services = [
  ['Residential Properties', Home], ['Commercial Properties', Building2], ['Agricultural Land', Leaf], ['Plot Buying & Selling', Landmark],
  ['Property Investment', TrendingUp], ['Rental Assistance', Users], ['Property Documentation', FileCheck2], ['Property Consultation', ShieldCheck]
] as const;
const stats = ['Trusted Local Experts', 'Verified Properties', 'Transparent Deals', 'Customer Satisfaction', 'Fast Documentation', 'Best Investment Guidance'];

function Counter({ value }: { value: number }) { const [n,setN]=useState(0); useEffect(()=>{let i=0; const t=setInterval(()=>{i+=Math.ceil(value/38); setN(Math.min(i,value)); if(i>=value) clearInterval(t);},30); return()=>clearInterval(t);},[value]); return <>{n}+</>; }

export default function HomePage() {
  const [menu,setMenu]=useState(false); const [light,setLight]=useState(false); const [testimonial,setTestimonial]=useState(0); const [loading,setLoading]=useState(true);
  const { scrollYProgress } = useScroll(); const scaleX = useSpring(scrollYProgress, { stiffness: 100, damping: 30 });
  useEffect(()=>{document.body.classList.toggle('light', light);},[light]);
  useEffect(()=>{const t=setTimeout(()=>setLoading(false),900); const c=setInterval(()=>setTestimonial(v=>(v+1)%testimonials.length),4200); return()=>{clearTimeout(t); clearInterval(c);};},[]);
  const nav = useMemo(()=>['About','Services','Properties','Why Us','Testimonials','Contact'],[]);
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#070706]"><div className="text-center"><div className="loader-shimmer relative mx-auto mb-5 h-20 w-20 overflow-hidden rounded-3xl border border-amber-300/40 bg-gradient-to-br from-amber-200 to-emerald-900"/><p className="font-[var(--font-poppins)] text-xl font-bold gold-text">Om Properties</p><p className="mt-2 text-sm text-white/55">Preparing premium listings...</p></div></main>;
  return <main className="overflow-hidden">
    <motion.div style={{scaleX}} className="fixed left-0 top-0 z-[70] h-1 w-full origin-left bg-amber-300" />
    <header className="fixed inset-x-0 top-0 z-50 mx-auto border-b border-white/10 bg-black/35 backdrop-blur-2xl">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href="#home" className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-amber-200 to-yellow-700 font-black text-black">OM</span><span><b className="block font-[var(--font-poppins)] text-lg">Om Properties</b><small className="text-amber-200/80">Kaithal • Jind</small></span></a><div className="hidden items-center gap-7 lg:flex">{nav.map(n=><a key={n} className="text-sm text-white/75 hover:text-amber-200" href={`#${n.toLowerCase().replace(' ','-')}`}>{n}</a>)}<Button size="sm" onClick={()=>location.href='#contact'}>Enquire Now</Button><button aria-label="Toggle theme" onClick={()=>setLight(!light)} className="rounded-full border border-white/15 p-2">{light?<Moon/>:<Sun/>}</button></div><button className="lg:hidden" onClick={()=>setMenu(!menu)} aria-label="Open menu">{menu?<X/>:<Menu/>}</button></nav>
      {menu && <div className="glass mx-5 mb-4 rounded-3xl p-5 lg:hidden">{nav.map(n=><a onClick={()=>setMenu(false)} key={n} className="block py-3" href={`#${n.toLowerCase().replace(' ','-')}`}>{n}</a>)}</div>}
    </header>
    <section id="home" className="relative flex min-h-screen items-center px-5 pt-24"><Image priority fill src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=85" alt="Luxury property exterior" className="object-cover"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(15,107,83,.38),transparent_30%),linear-gradient(90deg,rgba(0,0,0,.92),rgba(0,0,0,.45),rgba(0,0,0,.82))]"/><div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_.9fr]"><motion.div initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:.8}}><span className="glass rounded-full px-4 py-2 text-sm text-amber-100">Premium real estate advisors in Haryana</span><h1 className="mt-7 max-w-4xl font-[var(--font-poppins)] text-5xl font-extrabold leading-tight md:text-7xl">Your Trusted Property Partner in <span className="gold-text">Kaithal & Jind</span></h1><p className="mt-6 text-xl text-white/78">Buying • Selling • Investment • Commercial • Agricultural Lands</p><div className="mt-9 flex flex-wrap gap-4"><Button size="lg" onClick={()=>location.href='#properties'}>View Properties</Button><Button size="lg" variant="outline" onClick={()=>location.href='#contact'}>Contact Us</Button></div></motion.div><div className="glass dark-panel self-end rounded-[2rem] p-5"><div className="grid gap-3 md:grid-cols-4"><label className="md:col-span-2"><span className="text-xs text-white/60">Search locality</span><input className="mt-2 w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 outline-none" placeholder="Kaithal, Jind, Highway..."/></label><select className="self-end rounded-2xl border border-white/10 bg-black/40 px-4 py-3"><option>Property Type</option><option>Residential</option><option>Commercial</option><option>Agricultural</option></select><Button className="self-end"><Search className="mr-2 h-4 w-4"/>Search</Button></div></div></div></section>
    <section id="about" className="mx-auto max-w-7xl px-5 py-24"><div className="grid gap-10 lg:grid-cols-2"><div><p className="text-amber-300">About Us</p><h2 className="mt-3 font-[var(--font-poppins)] text-4xl font-bold">Local expertise with a luxury-standard client experience.</h2></div><p className="text-lg leading-8 text-white/70">Om Properties is a trusted property dealing company serving Kaithal and Jind with professional guidance for residential homes, commercial spaces, plots, agricultural land, and high-potential investments. Our team focuses on verified listings, transparent negotiation, legal-document assistance, and long-term customer satisfaction.</p></div></section>
    <section id="services" className="bg-white/[.03] px-5 py-24"><div className="mx-auto max-w-7xl"><h2 className="text-center font-[var(--font-poppins)] text-4xl font-bold">Services</h2><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(([s,Icon],i)=><motion.div whileHover={{y:-8}} key={s} className="glass dark-panel rounded-3xl p-6"><Icon className="mb-5 h-9 w-9 text-amber-300"/><h3 className="font-semibold">{s}</h3><p className="mt-3 text-sm text-white/58">Premium, genuine, and locally informed property support tailored to your goals.</p></motion.div>)}</div></div></section>
    <section id="properties" className="mx-auto max-w-7xl px-5 py-24"><h2 className="font-[var(--font-poppins)] text-4xl font-bold">Featured Properties</h2><div className="mt-10 grid gap-7 md:grid-cols-2 xl:grid-cols-4">{properties.map(p=><article key={p.title} className="glass dark-panel overflow-hidden rounded-[2rem]"><div className="relative h-64"><Image fill loading="lazy" src={p.image} alt={p.title} className="object-cover transition duration-500 hover:scale-105"/><span className="absolute left-4 top-4 rounded-full bg-emerald-900/80 px-3 py-1 text-xs">{p.type}</span></div><div className="p-5"><h3 className="text-xl font-bold">{p.title}</h3><p className="mt-2 flex items-center gap-2 text-white/60"><MapPin className="h-4 w-4"/>{p.location}</p><div className="my-4 flex justify-between text-sm"><b className="text-amber-300">{p.price}</b><span>{p.area}</span></div><Button className="w-full" variant="outline">View Details</Button></div></article>)}</div></section>
    <section id="why-us" className="px-5 py-24"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-3">{stats.map((s,i)=><div key={s} className="glass dark-panel rounded-3xl p-7"><Sparkles className="mb-4 text-amber-300"/><b className="text-3xl gold-text"><Counter value={[12,350,100,98,48,75][i]}/></b><p className="mt-2 text-white/70">{s}</p></div>)}</div></section>
    <section id="testimonials" className="mx-auto max-w-4xl px-5 py-24 text-center"><h2 className="font-[var(--font-poppins)] text-4xl font-bold">Client Testimonials</h2><motion.div key={testimonial} initial={{opacity:0,x:40}} animate={{opacity:1,x:0}} className="glass dark-panel mt-10 rounded-[2rem] p-10"><div className="mb-5 flex justify-center gap-1 text-amber-300">{Array.from({length:5}).map((_,i)=><Star key={i} fill="currentColor" />)}</div><p className="text-xl leading-8">“{testimonials[testimonial].text}”</p><b className="mt-6 block text-amber-200">{testimonials[testimonial].name}</b></motion.div></section>
    <section id="contact" className="bg-white/[.03] px-5 py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><div><h2 className="font-[var(--font-poppins)] text-4xl font-bold">Contact Om Properties</h2><p className="mt-4 text-white/65">Call, WhatsApp, or send your requirement. Our advisors will share verified options across Kaithal and Jind.</p><div className="mt-8 space-y-4 text-white/75"><p><Phone className="mr-2 inline text-amber-300"/>+91 98765 43210</p><p><Mail className="mr-2 inline text-amber-300"/>info@ompropertieskaithal.com</p><p><MapPin className="mr-2 inline text-amber-300"/>Near Pehowa Chowk, Kaithal, Haryana, India</p></div><iframe title="Om Properties map" className="mt-8 h-72 w-full rounded-3xl border-0 grayscale" loading="lazy" src="https://www.google.com/maps?q=Kaithal%20Haryana%20India&output=embed"/></div><form className="glass dark-panel grid gap-4 rounded-[2rem] p-6"><input className="rounded-2xl border border-white/10 bg-black/25 px-4 py-4" placeholder="Full name"/><input className="rounded-2xl border border-white/10 bg-black/25 px-4 py-4" placeholder="Phone / WhatsApp"/><select className="rounded-2xl border border-white/10 bg-black/25 px-4 py-4"><option>Residential Property</option><option>Commercial Property</option><option>Agricultural Land</option><option>Investment Guidance</option></select><textarea rows={5} className="rounded-2xl border border-white/10 bg-black/25 px-4 py-4" placeholder="Tell us your requirement"/><Button type="button" size="lg">Submit Enquiry</Button></form></div></section>
    <footer className="px-5 py-12"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-4"><b className="text-2xl gold-text">Om Properties</b><div><h3 className="mb-3 font-bold">Quick Links</h3>{nav.slice(0,4).map(n=><a className="block py-1 text-white/60" key={n} href={`#${n.toLowerCase().replace(' ','-')}`}>{n}</a>)}</div><div><h3 className="mb-3 font-bold">Services</h3>{services.slice(0,5).map(([s])=><p className="py-1 text-white/60" key={s}>{s}</p>)}</div><p className="text-white/60">© 2026 Om Properties. Premium real estate services for Kaithal & Jind.</p></div></footer>
    <a aria-label="WhatsApp" href="https://wa.me/919876543210" className="fixed bottom-24 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-emerald-600 shadow-2xl"><Phone/></a><a aria-label="Call" href="tel:+919876543210" className="fixed bottom-40 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-amber-400 text-black shadow-2xl"><Phone/></a><button aria-label="Scroll to top" onClick={()=>scrollTo({top:0,behavior:'smooth'})} className="fixed bottom-5 right-5 z-40 grid h-14 w-14 place-items-center rounded-full border border-white/15 bg-black/60 backdrop-blur"><ChevronUp/></button>
  </main>;
}
