import Image from 'next/image';
import Link from 'next/link';
import { Award, BellRing, Bot, BriefcaseBusiness, Building2, Calculator, FileCheck2, Heart, Home, Landmark, Leaf, Map, MessageCircle, Newspaper, Search, ShieldCheck, Sparkles, Star, TrendingUp, Users, Video } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PropertyCard } from '@/components/property/property-card';
import { ContactForm } from '@/components/shared/contact-form';
import { Reveal } from '@/components/layout/experience-shell';
import { company, properties, testimonials } from '@/data/site';

const services = [ ['Residential Properties', Home], ['Commercial Properties', Building2], ['Agricultural Land', Leaf], ['Plot Buying & Selling', Landmark], ['Property Investment', TrendingUp], ['Rental Assistance', Users], ['Documentation', FileCheck2], ['NRI & Legal Support', ShieldCheck] ] as const;
const platform = [ ['AI property assistant', Bot], ['Live chat & WhatsApp', MessageCircle], ['Mortgage / EMI tools', Calculator], ['Virtual 360° tours', Video], ['Saved searches', BellRing], ['Owner dashboards', BriefcaseBusiness] ] as const;
const locations = ['Kaithal', 'Jind', 'Ambala Road', 'Sector 20', 'Pehowa Chowk', 'Jind Bypass'];
const blogs = ['2026 Haryana property trends', 'How to verify a plot before registry', 'Best corridors for rental ROI'];

export default function HomePage() {
  const jsonLd = { '@context': 'https://schema.org', '@type': 'RealEstateAgent', name: company.name, telephone: company.phone, email: company.email, address: company.address, areaServed: company.serviceArea };
  return <main className="overflow-hidden">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <section className="relative flex min-h-screen items-center px-5 pt-24"><Image priority fill src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=85" alt="Luxury property exterior" className="object-cover scale-105"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(215,168,63,.28),transparent_28%),linear-gradient(90deg,rgba(0,0,0,.94),rgba(0,0,0,.42),rgba(0,0,0,.85))]"/><div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.05fr_.95fr]"><Reveal><span className="glass rounded-full px-4 py-2 text-sm text-amber-100">Premium real estate platform for Haryana growth corridors</span><h1 className="mt-7 max-w-4xl font-[var(--font-poppins)] text-5xl font-extrabold leading-tight md:text-7xl">Find, compare, visit, and close <span className="gold-text">verified property</span> with confidence.</h1><p className="mt-6 max-w-2xl text-xl text-white/78">A luxury dark, animation-rich experience for buying, selling, renting, investing, valuation, documentation, and advisory across Kaithal, Jind, and nearby markets.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/properties"><Button size="lg">Explore Listings</Button></Link><Link href="/contact"><Button size="lg" variant="outline">Schedule Visit</Button></Link></div></Reveal><Reveal delay={.15} className="glass dark-panel self-end rounded-[2rem] p-5"><form action="/properties" className="grid gap-3 md:grid-cols-4"><label className="md:col-span-2"><span className="text-xs text-white/60">Instant smart search</span><input name="q" className="mt-2 w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 outline-none" placeholder="City, area, budget, property ID..."/></label><select name="type" className="self-end rounded-2xl border border-white/10 bg-neutral-950 px-4 py-3"><option>All</option><option>Residential</option><option>Commercial</option><option>Agricultural</option></select><Button className="self-end" type="submit"><Search className="mr-2 h-4 w-4"/>Search</Button></form><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-white/5 p-3"><b className="gold-text text-2xl">12+</b><p className="text-xs text-white/55">Years</p></div><div className="rounded-2xl bg-white/5 p-3"><b className="gold-text text-2xl">350+</b><p className="text-xs text-white/55">Clients</p></div><div className="rounded-2xl bg-white/5 p-3"><b className="gold-text text-2xl">100%</b><p className="text-xs text-white/55">Verified</p></div></div></Reveal></div></section>
    <Section title="Unified premium platform" eyebrow="Everything integrated" text="Merged listing discovery, comparison, favorites, recently viewed flows, inquiry capture, calculators, maps, virtual-tour readiness, reviews, blogs, careers, services, and admin-ready structure into one polished experience." />
    <section id="services" className="bg-white/[.03] px-5 py-24"><div className="mx-auto max-w-7xl"><Reveal><h2 className="text-center font-[var(--font-poppins)] text-4xl font-bold">Complete Property Services</h2></Reveal><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(([service, Icon], i) => <Reveal key={service} delay={i*.04}><article className="glass dark-panel hover-lift rounded-3xl p-6"><Icon className="mb-5 h-9 w-9 text-amber-300"/><h3 className="font-semibold">{service}</h3><p className="mt-3 text-sm text-white/58">Verified options, site visits, negotiation, paperwork, and concierge support.</p></article></Reveal>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-amber-300">Featured listings</p><h2 className="font-[var(--font-poppins)] text-4xl font-bold">Ready-to-enquire properties</h2></div><Link href="/properties"><Button variant="outline">Browse all listings</Button></Link></div><div className="mt-10 grid gap-7 md:grid-cols-2 xl:grid-cols-3">{featured.map((property, i) => <Reveal key={property.id} delay={i*.08}><PropertyCard property={property} /></Reveal>)}</div></section>
    <section className="px-5 py-24"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-2"><Reveal className="glass dark-panel rounded-[2rem] p-8"><Map className="mb-4 h-10 w-10 text-amber-300"/><h2 className="text-3xl font-bold">Popular locations & map preview</h2><div className="mt-5 flex flex-wrap gap-3">{locations.map(l => <Link key={l} href={`/properties?q=${encodeURIComponent(l)}`} className="rounded-full border border-white/10 px-4 py-2 text-white/70 hover:border-amber-300 hover:text-amber-200">{l}</Link>)}</div><iframe title="Om Properties map" className="mt-8 h-72 w-full rounded-3xl border-0 grayscale" loading="lazy" src={company.officeMap}/></Reveal><Reveal delay={.12} className="grid gap-5 sm:grid-cols-2">{platform.map(([item, Icon]) => <div key={item} className="glass hover-lift rounded-3xl p-6"><Icon className="mb-4 text-emerald-200"/><h3 className="font-semibold">{item}</h3><p className="mt-2 text-sm text-white/55">Production-ready UI pattern prepared for future backend integration.</p></div>)}</Reveal></div></section>
    <section id="why-us" className="bg-white/[.03] px-5 py-24"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-4">{[['12+','years experience',Award],['350+','happy customers',Users],['75+','properties sold',Home],['4.9★','Google-style rating',Star]].map(([n,t,Icon]) => <article key={String(t)} className="glass dark-panel rounded-3xl p-7 text-center"><Icon className="mx-auto mb-4 text-amber-300"/><b className="text-4xl gold-text">{String(n)}</b><p className="mt-2 text-white/70">{String(t)}</p></article>)}</div></section>
    <section className="mx-auto max-w-7xl px-5 py-24"><div className="grid gap-8 lg:grid-cols-3"><div className="lg:col-span-1"><p className="text-amber-300">Trust & insights</p><h2 className="mt-3 text-4xl font-bold">Reviews, partners, awards, FAQs, and guides.</h2></div><div className="grid gap-5 lg:col-span-2 md:grid-cols-3">{testimonials.map((item) => <article key={item.name} className="glass dark-panel hover-lift rounded-[2rem] p-6"><div className="mb-4 flex gap-1 text-amber-300">{Array.from({length:5}).map((_,i)=><Star key={i} className="h-4 w-4" fill="currentColor" />)}</div><p className="text-sm leading-6 text-white/70">“{item.text}”</p><b className="mt-5 block text-amber-200">{item.name}</b><small className="text-white/50">{item.role}</small></article>)}</div></div><div className="mt-10 grid gap-5 md:grid-cols-3">{blogs.map(b => <Link key={b} href="/blog" className="glass hover-lift rounded-3xl p-6"><Newspaper className="mb-4 text-amber-300"/><h3 className="font-semibold">{b}</h3><p className="mt-2 text-sm text-white/55">SEO-friendly article preview with market education.</p></Link>)}</div></section>
    <section className="bg-white/[.03] px-5 py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><div><h2 className="font-[var(--font-poppins)] text-4xl font-bold">Contact Om Properties</h2><p className="mt-4 text-white/65">Call, WhatsApp, book a visit, request valuation, subscribe for alerts, or send a detailed requirement.</p><div className="mt-8 rounded-3xl border border-amber-300/20 bg-amber-300/10 p-5"><Heart className="mb-3 text-amber-300"/><b>Beautiful empty states, toast-ready forms, skeleton loaders, and success/error micro-interactions are built into the interface language.</b></div></div><ContactForm /></div></section>
  </main>;
}

function Section({ title, eyebrow, text }: { title: string; eyebrow: string; text: string }) { return <section className="mx-auto max-w-7xl px-5 py-24"><Reveal><div className="grid gap-10 lg:grid-cols-2"><div><p className="text-amber-300">{eyebrow}</p><h2 className="mt-3 font-[var(--font-poppins)] text-4xl font-bold">{title}</h2></div><p className="text-lg leading-8 text-white/70">{text}</p></div></Reveal></section>; }
