import Image from 'next/image';
import Link from 'next/link';
import { Building2, FileCheck2, Home, Landmark, Leaf, Search, ShieldCheck, Sparkles, Star, TrendingUp, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PropertyCard } from '@/components/property/property-card';
import { ContactForm } from '@/components/shared/contact-form';
import { company, properties, testimonials } from '@/data/site';

const services = [
  ['Residential Properties', Home], ['Commercial Properties', Building2], ['Agricultural Land', Leaf], ['Plot Buying & Selling', Landmark],
  ['Property Investment', TrendingUp], ['Rental Assistance', Users], ['Property Documentation', FileCheck2], ['Property Consultation', ShieldCheck]
] as const;

export default function HomePage() {
  const featured = properties.filter((property) => property.featured).slice(0, 3);
  const jsonLd = { '@context': 'https://schema.org', '@type': 'RealEstateAgent', name: company.name, telephone: company.phone, email: company.email, address: company.address, areaServed: company.serviceArea };
  return <main className="overflow-hidden">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <section className="relative flex min-h-screen items-center px-5 pt-24"><Image priority fill src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=85" alt="Luxury property exterior" className="object-cover"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(15,107,83,.38),transparent_30%),linear-gradient(90deg,rgba(0,0,0,.92),rgba(0,0,0,.45),rgba(0,0,0,.82))]"/><div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><span className="glass rounded-full px-4 py-2 text-sm text-amber-100">Premium real estate advisors in Haryana</span><h1 className="mt-7 max-w-4xl font-[var(--font-poppins)] text-5xl font-extrabold leading-tight md:text-7xl">Find verified property in <span className="gold-text">Kaithal & Jind</span></h1><p className="mt-6 text-xl text-white/78">Buy, sell, rent, and invest with local experts who handle site visits, negotiation, and documentation.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/properties"><Button size="lg">View Properties</Button></Link><Link href="/contact"><Button size="lg" variant="outline">Book Consultation</Button></Link></div></div><form action="/properties" className="glass dark-panel self-end rounded-[2rem] p-5"><div className="grid gap-3 md:grid-cols-4"><label className="md:col-span-2"><span className="text-xs text-white/60">Search locality</span><input name="q" className="mt-2 w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 outline-none" placeholder="Kaithal, Jind, Highway..."/></label><select name="type" className="self-end rounded-2xl border border-white/10 bg-neutral-950 px-4 py-3"><option>All</option><option>Residential</option><option>Commercial</option><option>Agricultural</option></select><Button className="self-end" type="submit"><Search className="mr-2 h-4 w-4"/>Search</Button></div></form></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24"><div className="grid gap-10 lg:grid-cols-2"><div><p className="text-amber-300">About Us</p><h2 className="mt-3 font-[var(--font-poppins)] text-4xl font-bold">Local expertise with a luxury-standard client experience.</h2></div><p className="text-lg leading-8 text-white/70">Om Properties serves customers with verified listings, transparent negotiation, legal-document coordination, and practical investment guidance for residential homes, commercial spaces, plots, agricultural land, and rentals.</p></div></section>
    <section id="services" className="bg-white/[.03] px-5 py-24"><div className="mx-auto max-w-7xl"><h2 className="text-center font-[var(--font-poppins)] text-4xl font-bold">Complete Property Services</h2><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(([service, Icon]) => <article key={service} className="glass dark-panel rounded-3xl p-6 transition hover:-translate-y-2"><Icon className="mb-5 h-9 w-9 text-amber-300"/><h3 className="font-semibold">{service}</h3><p className="mt-3 text-sm text-white/58">Premium, genuine, and locally informed support tailored to your goals.</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-amber-300">Featured listings</p><h2 className="font-[var(--font-poppins)] text-4xl font-bold">Ready-to-enquire properties</h2></div><Link href="/properties"><Button variant="outline">Browse all listings</Button></Link></div><div className="mt-10 grid gap-7 md:grid-cols-2 xl:grid-cols-3">{featured.map((property) => <PropertyCard key={property.id} property={property} />)}</div></section>
    <section id="why-us" className="px-5 py-24"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-3">{['12+ years local guidance','350+ customer requirements served','100% verified-before-share process'].map((stat) => <div key={stat} className="glass dark-panel rounded-3xl p-7"><Sparkles className="mb-4 text-amber-300"/><b className="text-3xl gold-text">{stat.split(' ')[0]}</b><p className="mt-2 text-white/70">{stat.replace(stat.split(' ')[0], '')}</p></div>)}</div></section>
    <section className="mx-auto max-w-4xl px-5 py-24 text-center"><h2 className="font-[var(--font-poppins)] text-4xl font-bold">Client Testimonials</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{testimonials.map((item) => <article key={item.name} className="glass dark-panel rounded-[2rem] p-6"><div className="mb-4 flex justify-center gap-1 text-amber-300">{Array.from({length:5}).map((_,i)=><Star key={i} className="h-4 w-4" fill="currentColor" />)}</div><p className="text-sm leading-6 text-white/70">“{item.text}”</p><b className="mt-5 block text-amber-200">{item.name}</b><small className="text-white/50">{item.role}</small></article>)}</div></section>
    <section className="bg-white/[.03] px-5 py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><div><h2 className="font-[var(--font-poppins)] text-4xl font-bold">Contact Om Properties</h2><p className="mt-4 text-white/65">Call, WhatsApp, or send your requirement. Our advisors will share verified options across Kaithal and Jind.</p><iframe title="Om Properties office map" className="mt-8 h-72 w-full rounded-3xl border-0 grayscale" loading="lazy" src={company.officeMap}/></div><ContactForm /></div></section>
  </main>;
}
